name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      action:
        description: added|deleted|changed
        required: true
      status:
        description: member status Paid Up|Left OGA|Deceased|...
        required: true
      firstname:
        description: member given name
        required: true
      lastname:
        description: member family name
        required: true
      id:
        description: member GOLD id
        required: true
      member_number:
        description: membership number
        required: false
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to find boats owned and update if needed
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python -m pip install poetry==2.1.3
    - run: python -m poetry install --no-root  
    - name: echo inputs
      run: |
        echo ${{ github.event.inputs.action }}
        echo ${{ github.event.inputs.status }}
        echo ${{ github.event.inputs.firstname }}
        echo ${{ github.event.inputs.lastname }}
        echo ${{ github.event.inputs.id }}
        echo ${{ github.event.inputs.member_number }}
        
