#!/usr/bin/env python3
from ruamel.yaml import YAML
import json
import sys

yaml = YAML(typ='safe')
yo = YAML()
yo.default_flow_style = False

def update(key, item):
  fn = f'picklists/{key}.yaml'
  with open(fn) as stream:
    l = yaml.load(stream)
  if l is not None:
    l.append(item)
    l.sort(key=lambda x: x['name'])
    o = [{'name': i['name'], 'id': i['id']} for i in l]
    print(o)
    with open(fn, 'w') as f:
      yo.dump(o, f)

if __name__ == '__main__':
  try:
    input = json.loads(sys.stdin.buffer.read())
  except:
    input = []
  for key in input.keys():
    print(key)
    update(key, input[key])
