#!/usr/bin/env python3
from ruamel.yaml import YAML
import json
import sys

yaml = YAML(typ='safe')
yo = YAML()
yo.default_flow_style = False

def update(key, item):
  fn = f'picklists/{key}.yaml'
  with open(fn) as stream:
    l = yaml.load(stream)
  if l is not None:
    if isinstance(item, list):
      for i in item:
        l.append(i)
    else:
      l.append(item)
    l.sort(key=lambda x: x['name'])
    o = [{'name': i['name'], 'id': i['id']} for i in l]
    print(o)
    with open(fn, 'w') as f:
      yo.dump(o, f)

if __name__ == '__main__':
  if len(sys.argv) == 2:
    data = sys.argv[1]
  else:
    data = sys.stdin.buffer.read()
  if data.strip() == b'' or data.strip() == '':
    print('no new items')
    exit()
  try:
    input = json.loads(data)
  except:
    print("can't parse stdin", data)
    input = {}
  for key in input.keys():
    k = key.replace('new_', '') # support both 'builder' and 'new_builder'
    update(k, input[key])
