#!/usr/bin/env python3
from ruamel.yaml import YAML
import json
import sys

yaml = YAML(typ='safe')
yo = YAML()
yo.default_flow_style = False

def update(key, item):
  fn = f'picklists/{key}.yaml'
  with open(fn) as stream:
    l = yaml.load(stream)
  if l is None:
    print("can't get yaml file for", key)
    return
  if isinstance(item, list):
    it = item
  else:
    it = [item]
  if isinstance(l[0], dict): # builders, ...
    for i in it:
      print(key, i)
      l.append(i)
    l.sort(key=lambda x: x['name'])
  else: # generic_type, ...
    for i in it:
      print(key, i['name'])
      l.append(i['name'])
    l.sort()
  with open(fn, 'w') as f:
    yo.dump(l, f)

if __name__ == '__main__':
  if len(sys.argv) == 2:
    data = sys.argv[1]
  else:
    data = sys.stdin.buffer.read()
  if data.strip() == b'' or data.strip() == '':
    print('no new items')
    exit()
  try:
    input = json.loads(data)
  except:
    print("can't parse stdin", data)
    input = {}
  for key in input.keys():
    k = key.replace('new_', '') # support both 'builder' and 'new_builder'
    update(k, input[key])
