#!/usr/bin/env python3
import sys
import ruamel.yaml
from os import listdir

yaml = ruamel.yaml.YAML(typ='safe')
yo = ruamel.yaml.YAML()
yo.default_flow_style = False

def seq(l):
    s = ruamel.yaml.comments.CommentedSeq(l)
    s.fa.set_flow_style()
    return s

def handle(dcs, name, oga_no):
  for dc in dcs:
    if dc['name'] == name:
      s = set(dc.get('examples', []))
      s.add(oga_no)
      dc['examples'] = seq(sorted(s))

def add_example_to_design_class(design_class_list, oga_no):
    with open(f'boat/{oga_no}/boat.yml') as stream:
      boat = yaml.load(stream)
      dc = boat.get('design_class', None)
      if dc is not None:
        handle(design_class_list, dc['name'], oga_no)

if __name__ == '__main__':
  if len(sys.argv) == 1:
    oga_nos = listdir('boat/')
  else:
    oga_nos = [sys.argv[1]]
  fn = 'picklists/design_class.yaml'
  with open(fn) as stream:
    design_class_list = yaml.load(stream)
  for oga_no in oga_nos:
    add_example_to_design_class(design_class_list, int(oga_no))
  with open(fn, 'w') as f:
    yo.dump(design_class_list, f)
