#!/usr/bin/env python3
import yaml
import json
import base64
import sys
from pathlib import Path
from helpers import merge_object, map_boat, dump, process_html

if __name__ == '__main__':
  with open("pickers.json", "r") as stream:
    pickers = json.load(stream)
  oga_no = sys.argv[1]
  if len(sys.argv) == 3:
    b64 = sys.argv[2]
    decoded = base64.b64decode(b64)
    changes = json.loads(decoded)
  else:
    changes = {}
  try:
    with open(f"boat/{oga_no}/boat.yml", "r", encoding='utf-8') as stream:
      boat = yaml.safe_load(stream)
  except:
    print(f"can't load boat {oga_no} existing yaml")
    boat = {}
  boat = process_html(boat)
  boat = map_boat(merge_object(boat, changes), pickers)
  outdir = f"boat/{boat['oga_no']}"
  Path(outdir).mkdir(parents=True, exist_ok=True)
  with open(f'{outdir}/boat.yml', 'w') as outfile:
    dump(boat, outfile)

