#!/usr/bin/env python3
import sys
from os import listdir
from pathlib import Path
import yaml
import json
from helpers import process_html, json_serialise

def jsonFromYaml(b):
  boat = None
  try:
    with open(f"boat/{b}/boat.yml", "r", encoding='utf-8') as stream:
      boat = yaml.safe_load(stream)
  except:
    print(b)
  if boat is not None:
    boat = process_html(boat)
    data = {
      "staticQueryHashes": [],
      "componentChunkName": "component---src-templates-boattemplate-jsx",
      "path": f"/boat/{b}",
      "result": {
        "pageContext": {
          "pathSlug": f"/boat/{b}",
          "home": "/",
          "absolute": "https://oga.org.uk",
          "boat": boat,
        }
      }
    }
    outdir = f"page-data/boat/{b}"
    Path(outdir).mkdir(parents=True, exist_ok=True)
    with open(f'{outdir}/page-data.json', 'w') as outfile:
      json.dump(data, outfile, sort_keys=True, default=json_serialise)

if __name__ == '__main__':
  if len(sys.argv) == 2:
    jsonFromYaml(sys.argv[1])
  else:
    boats = listdir('boat')
    for b in boats:
      jsonFromYaml(b)
