#!/usr/bin/env python3
import sys
from os import listdir
from pathlib import Path
import yaml
import json
from helpers import process_html, json_serialise

def upgrade(boat):
  for key in ['generic_type', 'designer', 'builder']:
    if key in boat and type(boat[key]) is dict:
      boat[key] = [boat[key]]
  return boat

def jsonFromYaml(b, fail=None):
  boat = None
  try:
    with open(f"boat/{b}/boat.yml", "r", encoding='utf-8') as stream:
      boat = yaml.safe_load(stream)
  except:
    msg = f'boat with OGA number {b} has invalid YAML.'
    if fail is None:
      print(msg)
    else:
      raise Exception(msg)
  if boat is not None:
    boat = upgrade(boat)
    boat = process_html(boat)
    data = {
      "staticQueryHashes": [],
      "componentChunkName": "component---src-templates-boattemplate-jsx",
      "path": f"/boat/{b}",
      "result": {
        "pageContext": {
          "pathSlug": f"/boat/{b}",
          "home": "/",
          "absolute": "https://oga.org.uk",
          "boat": boat,
        }
      }
    }
    outdir = f"page-data/boat/{b}"
    Path(outdir).mkdir(parents=True, exist_ok=True)
    with open(f'{outdir}/page-data.json', 'w') as outfile:
      json.dump(data, outfile, sort_keys=True, default=json_serialise)

def do_all(fail=None):
  boats = listdir('boat')
  for b in boats:
    jsonFromYaml(b, fail)

if __name__ == '__main__':
  if len(sys.argv) == 3:
    jsonFromYaml(sys.argv[1], sys.argv[2])
  elif len(sys.argv) == 2:
    n = sys.argv[1]
    if n == 'fail':
      do_all('fail')
    else:
      jsonFromYaml(n)
  else:
    do_all()