name: Check YAML
on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
            python-version: '3.13'
      - run: python -m pip install yamllint
      - name: check
        run: |-
          for f in `git show --name-only|grep '^[^ ].*boat\.yml'`
          do
            echo $f changed
            yamllint $f
          done
