name: Check YAML
on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
            python-version: '3.13'
      - run: python -m pip install poetry==2.1.3
      - run: python -m poetry install --no-root
      - name: test
        run: git show --name-only
      - name: create json boat files
        run: |
          python -m poetry run python make_boat_json_from_yaml fail
