name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values as base 64 encoded JSON'
        required: true
      email:
        description: 'email of person proposing the changes'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose an update to a boat
    steps:
    - uses: actions/checkout@v3
    - name: new boat test
      run: |
        if [ -f boat/${{ github.event.inputs.oga_no }}/boat.yml ]
        then
            echo "change=proposed updates to" >> $GITHUB_ENV
        else
            echo "change=create" >> $GITHUB_ENV
        fi
    - name: boat
      run: |
        echo ${{ github.event.inputs.data }} | ./make_boat_yaml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: up${{ github.event.inputs.oga_no }}
        title: ${{ env.action_state }} boat ${{ github.event.inputs.oga_no }} by ${{ github.event.inputs.email }}
        assignees: AlisonCable