name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose and update to a boat
    steps:
    - name: get sha
      run: |
        main_sha="$(gh api -H 'Accept: application/vnd.github+json' /repos/$OWNER/$REPO/git/matching-refs/heads/main --jq '.[0].object.sha')"
        echo 'MAIN='$main_sha >> $GITHUB_ENV
        echo $main_sha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
    - name: create branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'up${{ github.event.inputs.oga_no }}'
        sha: ${{ env.MAIN }}
    - name: log
      run: echo '{{ github.event.inputs.oga_no }}' | jq .

