name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose and update to a boat
    steps:
    - uses: actions/checkout@v3
    - name: show env
      run: env
    - name: test
      run: |
        git checkout -b up${{ github.event.inputs.oga_no }}
        echo '${{ github.event.inputs.data }}' | make_boat_yaml_from_stdin
        git add .
        git commit . -m "from user"
        git push -u origin up${{ github.event.inputs.oga_no }}