name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose and update to a boat
    steps:
    - uses: actions/checkout@v3
    - name: boat
      run: |
        echo ${{ github.event.inputs.data }} | ./make_boat_yaml
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: '.'
        new_branch: up${{ github.event.inputs.oga_no }}