name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: Boat OGA No
        required: true
      data:
        description: new values as base 64 encoded JSON
        required: true
      email:
        description: email of person proposing the changes
        required: true
      new:
        description: possible new designer, builder or design class
        required: false
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose an update to a boat
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
    - name: set branch name
      run: echo branch=up${{ github.event.inputs.oga_no }} >> $GITHUB_ENV
    - name: chose branch to checkout
      run: |
        if [[ $(git ls-remote --exit-code --heads origin ${{ env.branch }}) ]]
        then
          echo checkout=${{ env.branch }} >> $GITHUB_ENV
        else
          echo checkout=main >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ env.checkout }}
    - name: new boat test
      run: |
        if [ -f boat/${{ github.event.inputs.oga_no }}/boat.yml ]
        then
            echo "change=proposed updates to" >> $GITHUB_ENV
        else
            echo "change=create" >> $GITHUB_ENV
        fi
    - name: create branch if not existing
      run: |
        if [ "${{ env.checkout }}" = "main" ]
        then
          echo new branch
          git branch ${{ env.branch }}
          git push -u origin ${{ env.branch }}
          git checkout ${{ env.branch }}
        else
          echo checked out pr branch
        fi
    - name: new designer, builder or design class
      run: |
        echo '${{ github.event.inputs.new }}' | ./add_designer_items
    - name: boat
      run: |
        echo ${{ github.event.inputs.data }} | ./make_boat_yaml
        git add .
        if git diff --cached --exit-code; then
          echo CHANGES=0 >> $GITHUB_ENV
        else
          echo CHANGES=1 >> $GITHUB_ENV
        fi
        echo changes ${{ env.CHANGES == 1 }}
        true
    - name: run echo if changes
      if: ${{ env.CHANGES == 1 }}
      run: echo there are changes
    - name: run echo if no changes
      if: ${{ env.CHANGES == 0 }}
      run: echo there are no changes
    - name: commit and push if differences
      if: ${{ env.CHANGES == 1 }}
      run: |
        git config --global user.name ogauk  
        git config --global user.email boatregister@oga.org.uk
        git commit . -m "proposed change by ${{ github.event.inputs.email }}"
        git push origin ${{ env.branch }}
    - name: detect if pr exists
      if: ${{ env.CHANGES == 1 }}
      run: gh pr list --head ${{ env.branch }} -s open --json title --jq '. | length'| sed -e 's/^/PR=/' >> $GITHUB_ENV
    - name: Create Pull Request if none
      if: ${{ env.CHANGES == 1 && env.PR == 0 }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --assignee AlisonCable \
          --base main \
          --head ${{ env.branch }} \
          --title "${{ env.change }} boat ${{ github.event.inputs.oga_no }} by ${{ github.event.inputs.email }}" \
          --body "additional changes can be accumulated before merging"