name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values as base 64 encoded JSON'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose and update to a boat
    steps:
    - uses: actions/checkout@v3
    - name: boat
      run: |
        echo ${{ github.event.inputs.data }} | ./make_boat_yaml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: up${{ github.event.inputs.oga_no }}
        title: proposed updates to boat ${{ github.event.inputs.oga_no }}
        assignees: AlisonCable