name: propose update workflow
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: true
      data:
        description: 'new values as base 64 encoded JSON'
        required: true
      email:
        description: 'email of person proposing the changes'
        required: true
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to propose an update to a boat
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: new boat test
      run: |
        if [ -f boat/${{ github.event.inputs.oga_no }}/boat.yml ]
        then
            echo "change=proposed updates to" >> $GITHUB_ENV
        else
            echo "change=create" >> $GITHUB_ENV
        fi
    - name: set branch name
      run: echo branch=up${{ github.event.inputs.oga_no }} >> $GITHUB_ENV
    - name: create or switch to branch
      run: |
        if [[ $(git branch --list ${{ env.branch }}) ]]
        then
          git checkout ${{ env.branch }}
        else
          git checkout -b ${{ env.branch }}
        fi
    - name: boat
      run: |
        git config --global user.name ogauk  
        git config --global user.email boatregister@oga.org.uk
        echo ${{ github.event.inputs.data }} | ./make_boat_yaml
        git add .
        git commit . -m "proposed change by ${{ github.event.inputs.email }}"
        git push -u origin ${{ env.branch }}
    - name: Create Pull Request if none
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ 0 -eq $(gh pr list --head ${{ env.branch }} -s open --json title --jq '. | length') ]]
        then
          gh pr create \
            --assignee AlisonCable \
            --base main \
            --head ${{ env.branch }} \
            --title ${{ env.change }} boat ${{ github.event.inputs.oga_no }} by ${{ github.event.inputs.email }}
        fi
