name: Shuffle Editors Choice
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - run: python -m pip install poetry==2.1.3
      - run: python -m poetry install --no-root
      - name: shuffle editors_choice
        env:
          API_KEY: ${{ secrets.SMUGMUG_API_KEY }}
        run: |
          python -m poetry run python shuffle_editors_choice.py ${{ github.event.inputs.oga_no }}
          echo ok
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: '.'

