name: Shuffle Editors Choice
on:
  workflow_dispatch:
    inputs:
      oga_no:
        description: 'Boat OGA No'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: shuffle editors_choice
        run: |
          python3 shuffle_editors_choice.py ${{ github.event.inputs.oga_no }}
          echo ok
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: '.'

