name: upload boat json
permissions:
  id-token: write
  contents: read
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches-ignore:
      - main
jobs:
  deploy_source:
    name: upload json file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
            python-version: '3.13'
      - run: python -m pip install poetry==2.1.3
      - run: python -m poetry install --no-root
      - name: cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::651845762820:role/github-OIDC-Role-JdfwPtWdASUt
      - name: deploy
        run: |
          for f in `git show --name-only|grep '^[^ ].*boat\.yml'`
          do
            echo $f
            b=python -C "import sys\nprint(sys.argv[1].split('/')[1])" $f
            echo $b
            python -m poetry run python make_boat_json_from_yaml $b
            aws s3 cp page-data/boat/$b/page-data.json s3://boatregister-public/pending/$b.json
          done
