name: upload boat json
permissions:
  id-token: write
  contents: read
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches-ignore:
      - main
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
            python-version: '3.13'
      - run: python -m pip install poetry==2.1.3
      - run: python -m poetry install --no-root
      - name: create json boat files
        run: |
          python -m poetry run python make_boat_json_from_yaml
          echo ok
      - name: cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::651845762820:role/github-OIDC-Role-JdfwPtWdASUt
      - name: deploy
        run: |
          aws lambda update-function-code --function-name boatregister-api --zip-file fileb://lambda.zip